apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: somethings.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: Something
  definition:
    spec:
      name: string
      fullDNSName: string | default="a.b.c.d.example.com"
    status:
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas * 10}
  resources:
  - name: deployment
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${spec.name}
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: deployment
        template:
          metadata:
            labels:
              app: deployment
          spec:
            containers:
            - name: ${spec.name}-deployment
              image: nginx
              ports:
              - containerPort: 80
              env:
              - name: FULL_DNS_NAME
                value: ${spec.fullDNSName}
              - name: DNS_FIRST_PART
                value: ${spec.fullDNSName.split('.')[0]}
              - name: DNS_PARTIALS
                value: ${spec.fullDNSName.split('.').slice(0, 1).join('.')}
  - name: service
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ${spec.name}
        labels:
          app: deployment
          dns: ${spec.fullDNSName}
          partials: "${size(spec.fullDNSName.split('.')) > 2 ? spec.fullDNSName.split('.').slice(0, 3).join('.') : spec.fullDNSName}"
          first_part: ${spec.fullDNSName.split('.')[0]}
      spec:
        selector:
          app: deployment
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80