apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: deploymentservice.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: DeploymentService
    spec:
      name: string
      namespace: string | default=default
      service:
        enabled: boolean | default=false
    status:
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}
  resources:
  - name: deployment
    readyWhen:
      - ${deployment.spec.replicas == deployment.status.availableReplicas}
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${schema.spec.name}
      spec:
        replicas: 5
        selector:
          matchLabels:
            app: deployment
        template:
          metadata:
            labels:
              app: deployment
          spec:
            containers:
            - name: ${schema.spec.name}-deployment
              image: nginx
              ports:
              - containerPort: 80
  - name: service
    includeWhen:
    - ${schema.spec.service.enabled}
    template:
      apiVersion: v1
      kind: Service
      metadata:
        name: ${deployment.metadata.name}
        annotations:
          age: ${string(deployment.status.readyReplicas)}
      spec:
        selector:
          app: deployment
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80