name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v4
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: ./website

      - name: Build website
        run: bun build
        working-directory: ./website

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        working-directory: ./website
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    defaults:
      run:
        working-directory: ./website
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./websites/build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'